version: "3"

networks:
  default:
    external:
      name: ${NETWORK}

services:
  dotnet-webapp:
    image: ${IMAGE_PREFIX}dotnet-webapp:latest
    domainname: ${DOMAIN}
    restart: ${RESTART_POLICY}
    command: !
      --eureka.instance.metadataMap.version=4.1.5
    environment:
      - "constraint:hosttype==${DCP_BAG_HOST_TYPE}"
      - "KEY_ALIAS=${DOCKER_NETWORK_CERT_ALIAS}"
      - "affinity:container!=~*dotnet-webapp*"
    healthcheck:
        test: ["CMD-SHELL", "curl -v http://localhost:5000/admin/info"]
        interval: 30s
        timeout: 60s
        retries: 15
    deploy:
        mode: replicated
        replicas:  ${DCP_BAG_ORDER_SCALE}
        update_config:
          parallelism: 0
          delay: 10s
          max_failure_ratio: 1
        restart_policy:
          condition: on-failure
          delay: 10s
          max_attempts: 3
          window: 60s
        placement:
          constraints:
            - engine.labels.hosttype == ${DCP_BAG_HOST_TYPE}